name: Ejecucion Automata del Robot

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  ejecutar-robot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ejecutar el script principal
        run: python main.py

      - name: Guardar y subir cambios a GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Web actualizada automaticamente" || exit 0
          git push
     
