name: Ejecucion Automata del Robot

on:
  schedule:
    - cron: '0 8 * * *'  # Se ejecuta automáticamente todos los días a las 8:00 AM
  workflow_dispatch:      # Permite ejecución manual desde la pestaña Actions

permissions:
  contents: write

jobs:
  ejecutar-robot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Ejecutar script de Python
        run: python main.py

      - name: Guardar cambios en el repositorio
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html public/index.html
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-actualización de la web [skip ci]" && git push)
